booking/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url

from .views import (
    BookingDeleteView,
    BookingDetailView,
    BookingListMonthView,
    BookingListView,
    BookingUpdateNotesStaffView,
    BookingUpdateNotesUserView,
    CategoryCreateView,
    CategoryListView,
    CategoryUpdateView,
    download_calendar,
    LocationCreateView,
    LocationDetailView,
    LocationListView,
    LocationUpdateView,
    RotaCreateView,
    RotaDeleteView,
    RotaTypeCreateView,
    RotaTypeListView,
    RotaTypeUpdateView,
    RotaUpdateView,
)


urlpatterns = [
    url(regex=r"^$", view=BookingListView.as_view(), name="booking.list"),
    url(
        regex=r"^(?P<pk>\d+)/$",
        view=BookingDetailView.as_view(),
        name="booking.detail",
    ),
    url(
        regex=r"^(?P<pk>\d+)/delete/$",
        view=BookingDeleteView.as_view(),
        name="booking.delete",
    ),
    url(
        regex=r"^(?P<year>\d{4})/(?P<month>\d+)/$",
        view=BookingListMonthView.as_view(),
        name="booking.list.month",
    ),
    url(
        regex=r"^(?P<pk>\d+)/update/notes/staff/$",
        view=BookingUpdateNotesStaffView.as_view(),
        name="booking.update.notes.staff",
    ),
    url(
        regex=r"^(?P<pk>\d+)/update/notes/user/$",
        view=BookingUpdateNotesUserView.as_view(),
        name="booking.update.notes.user",
    ),
    url(
        regex=r"^category/$",
        view=CategoryListView.as_view(),
        name="booking.category.list",
    ),
    url(
        regex=r"^category/create/$",
        view=CategoryCreateView.as_view(),
        name="booking.category.create",
    ),
    url(
        regex=r"^category/(?P<pk>\d+)/update/$",
        view=CategoryUpdateView.as_view(),
        name="booking.category.update",
    ),
    url(
        regex=r"^download/$",
        view=download_calendar,
        name="booking.download.calendar",
    ),
    url(
        regex=r"^location/$",
        view=LocationListView.as_view(),
        name="booking.location.list",
    ),
    url(
        regex=r"^location/create/$",
        view=LocationCreateView.as_view(),
        name="booking.location.create",
    ),
    url(
        regex=r"^location/(?P<pk>\d+)/$",
        view=LocationDetailView.as_view(),
        name="booking.location",
    ),
    url(
        regex=r"^location/(?P<pk>\d+)/update/$",
        view=LocationUpdateView.as_view(),
        name="booking.location.update",
    ),
    url(
        regex=r"^rota/(?P<pk>\d+)/create/$",
        view=RotaCreateView.as_view(),
        name="booking.rota.create",
    ),
    url(
        regex=r"^rota/(?P<pk>\d+)/delete/$",
        view=RotaDeleteView.as_view(),
        name="booking.rota.delete",
    ),
    url(
        regex=r"^rota/(?P<pk>\d+)/update/$",
        view=RotaUpdateView.as_view(),
        name="booking.rota.update",
    ),
    url(
        regex=r"^rota/type/$",
        view=RotaTypeListView.as_view(),
        name="booking.rota.type.list",
    ),
    url(
        regex=r"^rota/type/create/$",
        view=RotaTypeCreateView.as_view(),
        name="booking.rota.type.create",
    ),
    url(
        regex=r"^rota/type/(?P<pk>\d+)/update/$",
        view=RotaTypeUpdateView.as_view(),
        name="booking.rota.type.update",
    ),
]

booking/models.py
# -*- encoding: utf-8 -*-
from dateutil.relativedelta import relativedelta
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils import timezone
from reversion import revisions as reversion

from base.model_utils import TimeStampedModel
from base.singleton import SingletonModel


def default_permission():
    return Permission.objects.get(slug=Permission.PUBLIC).pk


class BookingSettings(SingletonModel):

    display_categories = models.BooleanField(
        default=False, help_text=("Does this project use 'Categories'?")
    )
    display_permissions = models.BooleanField(
        default=False, help_text="Display permissions on the list of bookings."
    )
    display_locations = models.BooleanField(
        default=False, help_text=("Does this project use 'Locations'?")
    )
    display_rota = models.BooleanField(
        default=False, help_text=("Does this project use 'Rotas'?")
    )
    notes_user_staff = models.BooleanField(
        default=False,
        help_text=(
            "Allow a member of staff to edit notes for logged "
            "in users (and members of staff)"
        ),
    )
    pdf_heading = models.CharField(max_length=200, blank=True)

    class Meta:
        verbose_name = "Booking settings"

    def __str__(self):
        return "Booking settings (permissions: {}, notes: {})".format(
            self.display_permissions,
            self.notes_user_staff,
        )

    @property
    def edit_from_detail(self):
        """Do we edit events from the detail page?"""
        return self.notes_user_staff or self.display_rota


reversion.register(BookingSettings)


class CategoryManager(models.Manager):
    def create_category(self, description):
        category = self.model(
            description=description,
        )
        category.save()
        return category


class Category(TimeStampedModel):

    description = models.CharField(max_length=200)
    promote = models.BooleanField(default=False)
    routine = models.BooleanField(default=True)
    objects = CategoryManager()

    class Meta:
        ordering = ("description",)
        verbose_name = "Event type"
        verbose_name_plural = "Event types"

    def __str__(self):
        return "{}".format(self.description)


reversion.register(Category)


class LocationManager(models.Manager):
    def create_location(self, title):
        location = self.model(
            title=title,
        )
        location.save()
        return location


class Location(TimeStampedModel):

    title = models.CharField(max_length=200)
    address = models.TextField(blank=True)
    url = models.URLField(blank=True, null=True)
    url_map = models.URLField(blank=True, null=True)
    description = models.TextField(blank=True)
    picture = models.ImageField(upload_to="booking", blank=True)
    objects = LocationManager()

    class Meta:
        ordering = ("title",)
        verbose_name = "Location"
        verbose_name_plural = "Locations"

    def __str__(self):
        return "{}".format(self.title)


reversion.register(Location)


class PermissionManager(models.Manager):
    def create_permission(self, slug, description):
        permission = self.model(
            slug=slug,
            description=description,
        )
        permission.save()
        return permission

    def init_permission(self, slug, description):
        try:
            permission = self.model.objects.get(slug=slug)
            permission.description = description
            permission.save()
        except self.model.DoesNotExist:
            permission = self.create_permission(slug, description)
        return permission


class Permission(TimeStampedModel):

    PUBLIC = "public"
    STAFF = "staff"
    USER = "user"

    slug = models.SlugField(unique=True)
    description = models.CharField(max_length=200)
    objects = PermissionManager()

    class Meta:
        ordering = ("slug",)
        verbose_name = "Permission"
        verbose_name_plural = "Permissions"

    def __str__(self):
        return "{}".format(self.description)


reversion.register(Permission)


class BookingManager(models.Manager):
    def _current(self):
        """Return all current bookings."""
        return self.model.objects.exclude(deleted=True)

    def _eight_months(self):
        today = timezone.now().date()
        return today + relativedelta(months=8)

    def _filter_by_date(self, qs, start_date, end_date):
        """
        Filter booking objects which are in this date ranage.

        If the start date or end date are in the range, then include them.

        """
        return qs.filter(
            (Q(start_date__gte=start_date) & Q(start_date__lte=end_date))
            | (Q(end_date__lte=end_date) & Q(end_date__gte=start_date))
        )

    def _filter_by_month(self, qs, month, year):
        """
        Find booking objects which are in the month.

        If the start date or end date are in the month, then include them.

        """
        return qs.filter(
            (Q(start_date__month=month) & Q(start_date__year=year))
            | (Q(end_date__month=month) & Q(end_date__year=year))
        )

    def _four_months(self):
        today = timezone.now().date()
        return today + relativedelta(months=4)

    def _two_months(self):
        today = timezone.now().date()
        return today + relativedelta(months=2)

    def _public(self):
        return self._current().filter(
            permission__slug=Permission.PUBLIC,
            # status__publish=True,
        )

    def _public_calendar(self):
        return self._filter_by_date(
            self._public(), timezone.now().date(), self._two_months()
        )

    def _public_month(self, month, year):
        """Public bookings for this month."""
        return self._filter_by_month(self._public(), month, year)

    def _staff_calendar(self):
        four_months = self._four_months()
        # last day of this month
        end_date = four_months + relativedelta(months=+1, day=1, days=-1)
        return self._filter_by_date(
            self._current(), timezone.now().date(), end_date
        )

    def _staff_month(self, month, year):
        return self._filter_by_month(self._current(), month, year)

    def _user(self):
        return self._current().filter(
            permission__slug__in=(Permission.PUBLIC, Permission.USER),
        )

    def _user_calendar(self):
        return self._filter_by_date(
            self._user(), timezone.now().date(), self._two_months()
        )

    def _user_month(self, month, year):
        return self._filter_by_month(self._user(), month, year)

    def calendar(self, user):
        if user.is_staff:
            result = self._staff_calendar()
        elif user.is_authenticated:
            result = self._user_calendar()
        else:
            result = self._public_calendar()
        return result

    def month(self, user, month, year):
        if user.is_staff:
            result = self._staff_month(month, year)
        elif user.is_authenticated:
            result = self._user_month(month, year)
        else:
            result = self._public_month(month, year)
        return result

    def public_calendar_widget(self, start_date, end_date):
        return self._filter_by_date(self._public(), start_date, end_date)

    def public_promoted(self):
        return self._public().filter(
            start_date__gt=self._two_months(),
            start_date__lte=self._eight_months(),
            category__promote=True,
        )


class Booking(TimeStampedModel):

    permission = models.ForeignKey(
        Permission,
        default=default_permission,
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=200, blank=True)
    start_date = models.DateField(help_text="(dd/mm/yyyy)")
    start_time = models.TimeField(
        blank=True,
        null=True,
        help_text="Please enter in 24 hour format e.g. 19:00",
    )
    end_date = models.DateField(blank=True, null=True, help_text="(dd/mm/yyyy)")
    end_time = models.TimeField(
        blank=True,
        null=True,
        help_text="Please enter in 24 hour format e.g. 21:00",
    )
    location = models.ForeignKey(
        Location,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    description = models.TextField(blank=True)
    picture = models.ImageField(upload_to="booking", blank=True)
    notes_user = models.TextField(
        blank=True,
        help_text="Notes for your users who are logged into the site.",
    )
    notes_staff = models.TextField(
        blank=True,
        help_text="Notes for members of staff.",
    )
    deleted = models.BooleanField(default=False)
    objects = BookingManager()

    class Meta:
        ordering = ("start_date", "start_time")
        verbose_name = "Booking"
        verbose_name_plural = "Bookings"

    def __str__(self):
        end = ""
        if self.end_date:
            end = "-{}".format(self.end_date.strftime("%a %d %b %Y"))
        return "{}{}: {}".format(
            self.start_date.strftime("%a %d %b %Y"), end, self.title
        )

    def _is_in_the_past(self):
        return self.end_date and self.end_date < timezone.now().date()

    def clean(self):
        if self.end_date:
            if self.start_date > self.end_date:
                raise ValidationError(
                    "A booking cannot end before it has started."
                )
            if self.start_date == self.end_date:
                raise ValidationError(
                    "A booking cannot start and end on the same day."
                )
        if self._is_in_the_past():
            raise ValidationError("You cannot make a booking in the past.")

    def is_current(self):

booking/templates/booking/_booking_list.html
{% for b in booking_list %}
  {% ifchanged b.start_date.year b.start_date.month %}
    <div class="event">
      <div class="pure-g">
        <div class="pure-u-1 pure-u-md-6-24">
          <strong>{{ b.start_date|date:'F Y' }}</strong>
        </div>
        <div class="pure-u-1 pure-u-md-18-24">
        </div>
      </div>
    </div>
  {% endifchanged %}
  {% ifchanged b.start_date %}
    {% include 'booking/_booking.html' %}
  {% else %}
    {% include 'booking/_booking.html' with duplicate_date=True %}
  {% endifchanged %}
{% endfor %}

booking/templates/booking/_booking_notes_staff.html
{% if user.is_staff and b.notes_staff %}
  <div class="staff">
    {% autoescape off %}
      {{ b.notes_staff }}
    {% endautoescape %}
  </div>
{% endif %}

booking/templates/booking/_booking_notes_user.html
{% if user.is_authenticated and b.notes_user %}
  <div class="user">
    {% autoescape off %}
      {{ b.notes_user }}
    {% endautoescape %}
  </div>
{% endif %}

booking/templates/booking/_booking_rota.html
{% if user.is_authenticated and booking_settings.display_rota %}
  {% for rota in b.rota %}
    {% if forloop.first %}
      <br />
    {% endif %}
    <strong>{{ rota.rota.name }}</strong>:
    {{ rota.name }}
  {% endfor %}
{% endif %}

booking/templates/booking/_booking_status.html
{# only display this section if the context contains 'booking_edit' #}
{% if booking_edit %}
  <small>
    {% if booking_settings.display_permissions %}
      {% if b.permission.slug == 'staff' %}
        <span class="staff">
          <i class="fa fa-lock"></i>
      {% elif b.permission.slug == 'user' %}
        <span class="user">
          <i class="fa fa-user"></i>
      {% else %}
        <span>
          <i class="fa fa-globe"></i>
      {% endif %}
        {{ b.permission.slug }}
      </span>
      &nbsp;
    {% endif %}
    <a href="{% url 'booking.delete' b.pk %}">
      <i class="fa fa-times"></i>
      Delete
    </a>
    <br />
  </small>
{% endif %}

booking/templates/booking/_key.html
{% load static %}
<div class="l-box">
  <table class="pure-table pure-table-bordered">
    <thead>
      <tr>
        <th colspan='2'>Key to calendar</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          Available to book
        </td>
        <td>
          <img src="{% static 'project/img/booked-not.jpg' %}" />
        </td>
      </tr>
      <tr>
        <td>
          Booked in the morning
        </td>
        <td>
          <img src="{% static 'project/img/booked-morning.jpg' %}" />
        </td>
      </tr>
      <tr>
        <td>
          Booked in the afternoon
        </td>
        <td>
          <img src="{% static 'project/img/booked-afternoon.jpg' %}" />
        </td>
      </tr>
      <tr>
        <td>
          Booked all day
        </td>
        <td>
          <img src="{% static 'project/img/booked.jpg' %}" />
        </td>
      </tr>
    <tbody>
  </table>
</div>

booking/templates/booking/_settings.html
{% if user.is_staff %}
  <div class="pure-u-1 pure-u-md-1-4">
    <div class="pure-g">
      <div class="pure-u-1">
        <h4>Booking</h4>
      </div>
    </div>
    <div class="r-box">
      <a href="{% url 'booking.list' %}" class="pure-menu-link">
        <i class="fa fa-calendar"></i>
        Bookings
      </a>
    </div>
    {% if booking_settings.display_categories %}
      <div class="r-box">
        <a href="{% url 'booking.category.list' %}" class="pure-menu-link">
          <i class="fa fa-calendar"></i>
          Categories
        </a>
      </div>
    {% endif %}
    {% if booking_settings.display_locations %}
      <div class="r-box">
        <a href="{% url 'booking.location.list' %}" class="pure-menu-link">
          <i class="fa fa-calendar"></i>
          Locations
        </a>
      </div>
    {% endif %}
    {% if booking_settings.display_rota %}
      <div class="r-box">
        <a href="{% url 'booking.rota.type.list' %}" class="pure-menu-link">
          <i class="fa fa-male"></i>
          Rota Type
        </a>
      </div>
    {% endif %}
  </div>
{% endif %}

booking/templates/booking/base.html
{% extends 'dash/base.html' %}

booking/templates/booking/booking_form.html
{% extends "booking/base.html" %}

{% block sub_title %}
  Create a booking
{% endblock sub_title %}

{% block sub_heading %}
  Create a booking
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="l-box">
        {% include '_form.html' with legend='Booking' multipart=True %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block script_extra %}
  {% include 'base/_ckeditor.html' %}
{% endblock script_extra %}

booking/templates/booking/booking_list.html
{% extends "booking/base.html" %}
{% load static %}

{% block stylesheets_extra %}
  <link rel="stylesheet" href="{% static 'booking/css/booking.css' %}">
{% endblock stylesheets_extra %}

{% block title %}
  Bookings
{% endblock title %}

{% block sub_heading %}
  {{ sub_heading }}
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          <li class="pure-menu-item">
            <a href="{% url 'project.dash' %}" class="pure-menu-link">
              <i class="fa fa-reply"></i>
            </a>
          </li>
          {% if user.is_staff %}
            <li class="pure-menu-item">
              <a href="{% url 'booking.create' %}" class="pure-menu-link">
                <i class="fa fa-calendar-o"></i>
                New booking
              </a>
            </li>
          {% endif %}
          <li class="pure-menu-item">
            <a href="{% url 'booking.list.month' first_prev_month|date:'Y' first_prev_month|date:'m' %}" class="pure-menu-link">
              <i class="fa fa-backward"></i>
              {{ first_prev_month|date:"M Y" }}
            </a>
          </li>
          <li class="pure-menu-item">
            <a href="{% url 'booking.list.month' first_next_month|date:'Y' first_next_month|date:'m' %}" class="pure-menu-link">
              <i class="fa fa-forward"></i>
              {{ first_next_month|date:"M Y" }}
            </a>
          </li>
          {% if not display_today %}
            <li class="pure-menu-item">
              <a href="{% url 'booking.list' %}" class="pure-menu-link">
                <i class="fa fa-calendar"></i>
                Today
              </a>
            </li>
          {% endif %}
          <li class="pure-menu-item">
            <a href="{% url 'booking.download.calendar' %}" class="pure-menu-link">
              <i class="fa fa-cloud-download"></i>
              Download
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  {% include 'booking/_booking_list.html' %}
{% endblock content %}

booking/templates/booking/location_detail.html
{% extends 'booking/base.html' %}

{% block title %}
  {{ object.title }}
{% endblock title %}

{% block sub_heading %}
  {{ object.title }}
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
          {% if user.is_staff %}
            <li class="pure-menu-item">
              <a href="{% url 'project.dash' %}" class="pure-menu-link">
                <i class="fa fa-reply"></i>
              </a>
            </li>
            <li class="pure-menu-item">
              <a href="{% url 'booking.location.update' object.pk %}" class="pure-menu-link">
                <i class="fa fa-edit"></i>
                Edit location
              </a>
            </li>
            <li class="pure-menu-item">
              <a href="{% url 'booking.location.list' %}" class="pure-menu-link">
                <i class="fa fa-calendar"></i>
                Locations
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
      {% include 'booking/_location.html' with o=object %}
    </div>
  </div>
{% endblock content %}

booking/templates/booking/location_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Event location
{% endblock sub_title %}

{% block sub_heading %}
  Event location
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="l-box">
        {% include '_form.html' with legend='Location' multipart=True %}
      </div>
    </div>
  </div>
{% endblock content %}

{% block script_extra %}
  {% include 'base/_ckeditor.html' %}
{% endblock script_extra %}

booking/templates/booking/rota_remove_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Rota
{% endblock sub_title %}

{% block sub_heading %}
  Remove {{ object.name }} ({{ object.rota.name }}) from the rota?
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="l-box">
        Are you sure you want to remove <strong>{{ object.name }}</strong>
        ({{ object.rota.name }}) from the rota?
      </div>
    </div>
  </div>
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="l-box">
        {% include '_form.html' with submit='Remove from rota' %}
      </div>
    </div>
  </div>
{% endblock content %}

booking/templates/booking/rotatype_form.html
{% extends 'dash/base.html' %}

{% block sub_title %}
  Rota type
{% endblock sub_title %}

{% block sub_heading %}
  Rota type
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <div class="l-box">
        {% include '_form.html' with legend='Rota type' %}
      </div>
    </div>
  </div>
{% endblock content %}